name: Build and Publish

on:
  push:
    branches: [main]


env:
  GIT_PR_SHA: ${{github.event.pull_request.head.sha}}
  GIT_PR_SHA_SHORT: "${{ env.GIT_PR_SHA:0:10 }}"

jobs:
  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: test-task
        run: |
          IMAGE_TAG=$(git log -1 --pretty=format:%h)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GIT_PR_SHA_SHORT} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GIT_PR_SHA_SHORT}

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            tag=`git log -1 --pretty=format:%h`; sed -i "s/test-task:.*/test-task:${GIT_PR_SHA_SHORT}/" docker-compose.yml
            sudo docker-compose up -d